fintoc-com/fintoc-node

.npmrc

Add a .npmrc file to authenticate to npm
None.
None.

Fix npm auth

---

.github/workflows/release.yml

Use the npm token as a global env variable for the npm release job
None.
None.

Fix npm auth on install and build

---

.github/workflows/release.yml

**Bis**: Original PR can be found [here](https://github.com/fintoc-com/fintoc-node/pull/4).
- Add support for every endpoint and resource currently supported by the API itself
- Every resource now includes a `serialize` method to serialize the resource into an object.
- Add tests to the SDK to at least have 100% of coverage
- Document the library's capabilities a bit better (user-facing documentation)
- Change the interface to interact with almost every resource. Refer to [the documentation](https://github.com/fintoc-com/fintoc-node/blob/master/README.md) for more information.
- Remove superfluous methods like `showAccounts` that don't fit inside the SDK paradigm.
- Fix date management issues that bugged the library

Release 1.0.0

---

.npmrc

Remove unnecessary .npmrc file
None.
None.

Remove .npmrc file from the repository

---

README.md
package.json

Update a link on the `README.md` file that pointed to PyPi and add links to the `package.json` file.
None.
None.

Update some links through the documentation

---

README.md
src/lib/core.ts
src/lib/managers/index.ts
src/lib/managers/paymentIntentsManager.ts
src/lib/resources/movement.ts
src/lib/resources/paymentIntent.ts

This Pull Request integrates the Payment Intents functionality. It adds the `PaymentIntent` object and the `PaymentIntentsManager` object attached to the `Fintoc` object. It also documents the functionality.
None.
None.

Integrate Payment Intents

---

package.json
src/lib/version.ts

Prepare 1.1.0 release

---

.github/workflows/linters.yml
.github/workflows/release.yml
.github/workflows/tests.yml
src/types/resourceArguments.ts

Resources weren't being allowed to be passed with a level of nesting, so the following code would fail on the TS compiler:
```ts
import { Fintoc } from './src';
const fintocClient = new Fintoc('SOME_SECRET_KEY');
fintocClient.paymentIntents.create({
a: 1000,
recipient_account: {
holder_id: '111111',
number: '121212121212',
anotherValue: {
key: true,
}
},
});
```
None.
Some updates to the versions of the CI stuff.

Allow nested parameters on resources

---

package.json
src/lib/version.ts

Pre-release: prepare 1.1.1 release

---

package.json
src/lib/version.ts

pre-release: prepare 1.1.2 release

---

README.md
example/webhook.js
src/index.ts
src/lib/errors.ts
src/lib/webhook.ts
src/spec/webhook.spec.ts

This PR adds webhook signature validation functionality to ensure the authenticity of incoming webhooks from Fintoc. It supports timestamp validation with configurable tolerance.
None.
None.

feat: add webhook signature header verification

---

src/lib/webhook.ts
src/spec/integration.spec.ts
src/spec/mocks/client/response.ts

Add integrations tests for all API Endpoints that check that the library is calling the correct API url with correct parameters
None.
None.

Integration tests

---

package.json
src/lib/version.ts

Prepare 1.2.0 release
None.
None.

pre-release: prepare 1.2.0 release

---

src/lib/managers/v2/transfersManager.ts
src/spec/integration.spec.ts

Add support for return transfer method on the transfers endpoint
None.
None.

[TRNF-3300] add return action to sdk

---

package.json
src/lib/version.ts

[Description of the pull request]
[Additional actions that have to be done for the pull request to work (such as adding a secret to the repository)]
None.
[Changes done in this pull request that are additional to the purpose of the branch (such as formatting code or deleting files)]
None.

pre-release: prepare 1.3.0 release

---

package.json
src/lib/version.ts

Prepare 1.4.0 release with version bump.
None.
None.

pre-release: prepare 1.4.0 release

---

package.json
src/lib/managers/v2/accountsManager.ts
src/lib/managers/v2/index.ts
src/lib/managers/v2/movementsManager.ts
src/lib/resources/v2/index.ts
src/lib/resources/v2/movement.ts
src/lib/version.ts
src/spec/integration.spec.ts

- Add Movements v2 manager
None.
None.

[TRNF-3685] Feat/add movements v2

---

package.json
src/lib/managers/v2/accountsManager.ts
src/lib/managers/v2/index.ts
src/lib/managers/v2/movementsManager.ts
src/lib/resources/v2/index.ts
src/lib/resources/v2/movement.ts
src/lib/version.ts
src/spec/integration.spec.ts

- Add Movements v2 manager
[None]
[None]

Release 1.6.0

---

src/lib/core.ts
src/lib/managers/index.ts
src/lib/managers/refundsManager.ts
src/lib/resources/refund.ts
src/spec/integration.spec.ts

This `PR` add the resource `Refund` with its corresponding manager.
None.
None.

Feat add refunds

---

package.json
src/lib/version.ts

Prepare 1.7.0 release with version bump.
None.
None.

pre-release: prepare 1.7.0 release
